# SITE CONFIGURATION
title: IN2WISE TECH # your site title
author: WHUI KIM # You :P
description: > # Meta description of Homepage
  Welcome to our tech blog. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://in2wise-tech.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Whui Kim
social:
  name: Whui Kim
  links:
    - https://github.com/in2wise-khsunkh

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Blog', link: '/blog'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Artificial Intelligence Platform Leader.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: khsunkh@in2wise.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  in2wise-khsunkh # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: khsunkh # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
